### PR TITLE
podman 4.4.3

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #19
Fixes #33 
Fixes #34 
Fixes #35 
Fixes #36 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge/podman This is ready for review/merge.

**Review by dhirschfeld — APPROVED** [review]

**Comment by dhirschfeld** [comment]
LGTM but since @manics has been more active here I'll give him some time to take a look himself.

**Comment by xhochy** [comment]
@dhirschfeld I would merge this tomorrow, OK? Seems like @manics is currently busy with other things.

**Comment by dhirschfeld** [comment]
Sorry, fell off my radar, merging now!

**Comment by manics** [comment]
Sorry, too much other stuff to do! Thanks for fixing and reviewing.

**Pull request merged**
